FlagGame/Models/Flag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FlagGame.Models
{
    public class Flag
    {
        public int ID { get; }
        public string CountryName { get; set; }
        public string FlagFile { get; set; }

        public Flag(int id, string countryName, string flagFile)
        {
            ID = id;
            CountryName = countryName;
            FlagFile = flagFile;
        }
    }
}

FlagGame/Models/Game.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FlagGame.Models
{
    public class Game
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public List<Question> Questions { get; }

        public Game()
        {
            var questionsGenerator = new QuestionsGenerator();
            Questions = questionsGenerator.Generate();
        }

        public Question NextQuestion()
        {
           return Questions.Where(x => x.Answered() == false).FirstOrDefault();
        }
    }
}

FlagGame/Models/Question.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FlagGame.Models
{
    public class Question
    {

        public int ID { get; }
        public int Score { get; set; }
        public Flag Flag { get; set; }
        public List<String> WrongOptions { get; set; }
        public string answer { get; set; }

        public Question(int id, int score, Flag flag, List<string> wrongOptions)
        {
            ID = id;
            Score = score;
            Flag = flag;
            WrongOptions = wrongOptions;
        }
        
        public List<String> Options()
        {
            var random = new Random();
            var options = WrongOptions;
            options.Add(Flag.CountryName);
            return options.OrderBy(order => random.Next()).ToList();
        }

        public bool Answered()
        {
            return answer != null;
        }

    }
}

FlagGame/Models/QuestionsGenerator.cs
using FlagGame.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;

namespace FlagGame.Models
{
    public class QuestionsGenerator
    {

        private List<Flag> flags;

        public QuestionsGenerator()
        {
            flags = new FlagRepository().All();
        }

        public List<Question> Generate()
        {
            var questions = new List<Question>();
            
            foreach(var flag in flags)
            {
                var score = new Random().Next(100);
                var wrongOptions = GenerateWrongOptions(flag);
                questions.Add(new Question(questions.Count + 1, score, flag, wrongOptions));
            }
            return questions;
        }

        private List<String> GenerateWrongOptions(Flag flag)
        {
            return flags.Where(x => x.ID != flag.ID).Take(3).Select(f => f.CountryName).ToList();
        }
    }
}

FlagGame/Controllers/GamesController.cs
using FlagGame.Models;
using FlagGame.Repositories;
using System.Net;
using System.Web.Mvc;

namespace FlagGame.Controllers
{
    public class GamesController : Controller
    {
        private IGameRepository repository;

        public GamesController(IGameRepository repository)
        {
            this.repository = repository;
        }
        // GET: Games
        public ActionResult Index()
        {
            return View(repository.All());
        }

        // GET: Games/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserName")] Game game)
        {
            if (ModelState.IsValid)
            {
                repository.Save(game);                
                return RedirectToAction("Details", new { id = game.ID });
            }

            return View(game);
        }

        // GET: Games/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var game = repository.Find(id.Value);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }
    }


}

FlagGame/Controllers/QuestionsController.cs
using FlagGame.Repositories;
using System.Net;
using System.Web.Mvc;

namespace FlagGame.Controllers
{
    public class QuestionsController : Controller
    {
        private IGameRepository repository;

        public QuestionsController(IGameRepository repository)
        {
            this.repository = repository;
        }

        // GET: Questions/Details/5?gameId=1
        public ActionResult Details(int? id, int? gameId)
        {
            if (id == null && gameId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var game = repository.Find(gameId.Value);
            if (game == null) { return HttpNotFound(); }

            var question = game.Questions.Find(x => x.ID == id.Value);
            if (question == null) { return HttpNotFound(); }
            return View(question);
        }
    }
}

FlagGame/Views/Games/Create.cshtml
@model FlagGame.Models.Game

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Game</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

FlagGame/Views/Games/Details.cshtml
@model FlagGame.Models.Game

@{
    ViewBag.Title = String.Concat(Model.UserName, " Game");
}

<h2>@Html.Raw(String.Concat(Model.UserName, " Game"))</h2>

<div>
    <h4></h4>
    <hr />
    @Html.ActionLink("Proxima Pergunta", "Details", "Questions", new { gameId = Model.ID, id = Model.NextQuestion().ID }, null);
</div>

FlagGame/Views/Games/Index.cshtml
@model IEnumerable<FlagGame.Models.Game>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

FlagGame/Views/Questions/Details.cshtml
@model FlagGame.Models.Question

@{
    ViewBag.Title = "Details";
}

<h2>De que pais eh esta bandeira?</h2>

<div>
    <h4>Acerte a bandeira!!!</h4>
    <hr />
    <div class="row">
        <div class="col-md-6">
           <img class="img-responsive" src='@Url.Content("~/Content/images/" + Model.Flag.FlagFile)' />
        </div>
        <div class="col-md-6">
            @{ foreach (var option in Model.Options()) {
                @Html.RadioButton("answer", option)
                @Html.Label(option)
                    }
            }
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FlagGame/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Flag Game</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Flag Game", "Index", "Game", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>